---
title: "First Knit"
author: "Cynthia Cornejo"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.
  
### my answer     
  I attended Knight High School and graduated in 2021. After high school I attended CSULA for two years but then transferred to AVC because I wanted to per sue something different. Comparing both math and English to each other, Id say that English has always been an easier subject for me because I enjoy reading and writing. Math is a little more complicated for me to understand because of the different ways you can use numbers to get an answer that eventually its all confusing to me. I always succeeded in all my English courses. I enjoyed getting assigned to read different books and then got assigned to write about them.   

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
The computer I have access to at home is an apple mac computer. From a scale from 1 to 10 Id say I am a solid 6 when it comes to computer technology, I don't know much about computers besides the basics. My internet access at home is good and doesn't fail often.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
I would prefer that my classmates and instructor call me Cynthia.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
I would like to achieve a psychology career. A college subject that would benefit me would be basic psych classes that will help me get there. Im trying to achieve a psychology degree.  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
 I've never been to a foreign country but I would like to go to Mexico.Ive nevr been to the military nor do I know ,much about it, but I think I would join the marines instead because I like the ocean. 
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




